### Login request
POST https://extranet.qteam.be/VPLD/rest.logbook.cls?func=login
Content-Type: application/json

{
  "user": "scan",
  "password": "scan"
}

### SAL1A2B4XSA490093
GET https://db.vin/api/v1/vin/SJNFDAJ11U1152220

### Register request

POST https://api.automotivapi.com/v1/auth/register 
  Content-Type: application/json
  {
    "email": "jan.vanlemmens@telenet.be"
    }'

### SAL1A2B4XSA490093
GET https://vinspy.eu/check/?vin=SAL1A2B4XSA490093

### scrape
### SAL1A2B4XSA490093 Beschikbare - data-model
GET https://www.autogids.be/merk--volkswagen/modellen.html